# The absolute path to the root directory of the project. Both Drupal VM and
# the config file need to be contained within this path.
ENV['VM_PROJECT_ROOT'] = "#{__dir__}"
# The relative path from the project root to the config directory where you
# placed your config.yml file.
ENV['VM_CONFIG_DIR'] = ""
# The relative path from the project root to the directory where Drupal VM is located.
ENV['VM_DIR'] = "vendor/melvinloos/dev-vm"

# Load the real Vagrantfile
load "#{__dir__}/#{ENV['VM_DIR']}/Vagrantfile"
